export const isBin = require("./isBin")
export const isDec = require("./isDec")
export const isHex = require("./isHex")
export const toBin = require("./toBin")
export const toDec = require("./toDec")
export const toHex = require("./toHex")
